# -*- coding: utf-8 -*-
"""databuild.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lQ0bz65bsJl6BpsoSSZQr8NImNtylDy-
"""
from sklearn import preprocessing

def load_and_standardize_data(df):
  df = df.values.reshape(-1, df.shape[1]).astype('float32')
  # standardize values
  scaler = preprocessing.StandardScaler()
  return df, scaler

import torch
from torch.utils.data import Dataset, DataLoader

class DataBuilder(Dataset):
  def __init__(self, df):
    self.df, self.standardizer = load_and_standardize_data(df)
    self.x = torch.from_numpy(self.df)
    self.len = self.x.shape[0]

  def __getitem__(self,index):
      return self.x[index]
  
  def __len__(self):
      return self.len